"""v0.2 schema tv episode and webdav mode

Revision ID: 95cdc35859db
Revises: 9bab2d713c32
Create Date: 2026-05-19 12:16:46.766976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95cdc35859db'
down_revision: Union[str, Sequence[str], None] = '9bab2d713c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libraries', sa.Column('strm_mode', sa.String(length=32), nullable=False, server_default='cd2_local'))
    op.add_column('libraries', sa.Column('webdav_base_url', sa.String(length=512), nullable=True))
    op.add_column('libraries', sa.Column('webdav_path_prefix', sa.String(length=512), nullable=True))
    op.add_column('media_items', sa.Column('season', sa.Integer(), nullable=True))
    op.add_column('media_items', sa.Column('episode', sa.Integer(), nullable=True))
    op.add_column('media_items', sa.Column('episode_title', sa.String(length=256), nullable=True))
    op.add_column('media_items', sa.Column('parent_tmdb_id', sa.String(length=32), nullable=True))
    op.add_column('media_items', sa.Column('subtitle_paths', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_media_items_parent_tmdb_id'), 'media_items', ['parent_tmdb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_items_parent_tmdb_id'), table_name='media_items')
    op.drop_column('media_items', 'subtitle_paths')
    op.drop_column('media_items', 'parent_tmdb_id')
    op.drop_column('media_items', 'episode_title')
    op.drop_column('media_items', 'episode')
    op.drop_column('media_items', 'season')
    op.drop_column('libraries', 'webdav_path_prefix')
    op.drop_column('libraries', 'webdav_base_url')
    op.drop_column('libraries', 'strm_mode')
    # ### end Alembic commands ###
