"""initial schema

Revision ID: 9bab2d713c32
Revises: 
Create Date: 2026-05-19 11:39:50.796095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bab2d713c32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('drive_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credentials_enc', sa.String(length=2048), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_path', sa.String(length=512), nullable=False),
    sa.Column('target_strm_path', sa.String(length=512), nullable=False),
    sa.Column('cd2_mount_prefix', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('drive_account_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_url', sa.String(length=1024), nullable=False),
    sa.Column('share_password', sa.String(length=64), nullable=True),
    sa.Column('target_drive_account_id', sa.Integer(), nullable=True),
    sa.Column('target_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('original_title', sa.String(length=256), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.String(length=32), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('source_file_path', sa.String(length=1024), nullable=False),
    sa.Column('source_file_size', sa.BigInteger(), nullable=False),
    sa.Column('source_file_hash', sa.String(length=64), nullable=True),
    sa.Column('strm_path', sa.String(length=1024), nullable=True),
    sa.Column('nfo_path', sa.String(length=1024), nullable=True),
    sa.Column('poster_path', sa.String(length=1024), nullable=True),
    sa.Column('fanart_path', sa.String(length=1024), nullable=True),
    sa.Column('scrape_status', sa.String(length=16), nullable=False),
    sa.Column('scrape_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_path')
    )
    op.create_index(op.f('ix_media_items_library_id'), 'media_items', ['library_id'], unique=False)
    op.create_index(op.f('ix_media_items_tmdb_id'), 'media_items', ['tmdb_id'], unique=False)
    op.create_table('scan_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_tasks_library_id'), 'scan_tasks', ['library_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_tasks_library_id'), table_name='scan_tasks')
    op.drop_table('scan_tasks')
    op.drop_index(op.f('ix_media_items_tmdb_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_library_id'), table_name='media_items')
    op.drop_table('media_items')
    op.drop_table('transfer_tasks')
    op.drop_table('libraries')
    op.drop_table('drive_accounts')
    # ### end Alembic commands ###
