"""v0.3 library extensions

Revision ID: 32a390f20d21
Revises: 95cdc35859db
Create Date: 2026-05-20 03:48:54.287263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a390f20d21'
down_revision: Union[str, Sequence[str], None] = '95cdc35859db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libraries', sa.Column('strm_extensions', sa.String(length=1024), nullable=False, server_default='.mp4;.mkv;.ts;.iso;.rmvb;.avi;.mov;.mpeg;.mpg;.wmv;.3gp;.asf;.m4v;.flv;.m2ts;.tp;.f4v'))
    op.add_column('libraries', sa.Column('metadata_extensions', sa.String(length=1024), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libraries', 'metadata_extensions')
    op.drop_column('libraries', 'strm_extensions')
    # ### end Alembic commands ###
