"""v0.3 scrape enabled flag

Revision ID: 55988df4d7ef
Revises: 32a390f20d21
Create Date: 2026-05-20 03:56:17.286899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55988df4d7ef'
down_revision: Union[str, Sequence[str], None] = '32a390f20d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libraries', sa.Column('scrape_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libraries', 'scrape_enabled')
    # ### end Alembic commands ###
